/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStockRouteImport } from './routes/dashboard.stock'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRentalsRouteImport } from './routes/dashboard.rentals'
import { Route as DashboardPriceListRouteImport } from './routes/dashboard.price-list'
import { Route as DashboardGroupToolsRouteImport } from './routes/dashboard.group-tools'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStockRoute = DashboardStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRentalsRoute = DashboardRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPriceListRoute = DashboardPriceListRouteImport.update({
  id: '/price-list',
  path: '/price-list',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupToolsRoute = DashboardGroupToolsRouteImport.update({
  id: '/group-tools',
  path: '/group-tools',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/group-tools': typeof DashboardGroupToolsRoute
  '/dashboard/price-list': typeof DashboardPriceListRoute
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stock': typeof DashboardStockRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/group-tools': typeof DashboardGroupToolsRoute
  '/dashboard/price-list': typeof DashboardPriceListRoute
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stock': typeof DashboardStockRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/group-tools': typeof DashboardGroupToolsRoute
  '/dashboard/price-list': typeof DashboardPriceListRoute
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stock': typeof DashboardStockRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/group-tools'
    | '/dashboard/price-list'
    | '/dashboard/rentals'
    | '/dashboard/settings'
    | '/dashboard/stock'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/group-tools'
    | '/dashboard/price-list'
    | '/dashboard/rentals'
    | '/dashboard/settings'
    | '/dashboard/stock'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/group-tools'
    | '/dashboard/price-list'
    | '/dashboard/rentals'
    | '/dashboard/settings'
    | '/dashboard/stock'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stock': {
      id: '/dashboard/stock'
      path: '/stock'
      fullPath: '/dashboard/stock'
      preLoaderRoute: typeof DashboardStockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rentals': {
      id: '/dashboard/rentals'
      path: '/rentals'
      fullPath: '/dashboard/rentals'
      preLoaderRoute: typeof DashboardRentalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/price-list': {
      id: '/dashboard/price-list'
      path: '/price-list'
      fullPath: '/dashboard/price-list'
      preLoaderRoute: typeof DashboardPriceListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/group-tools': {
      id: '/dashboard/group-tools'
      path: '/group-tools'
      fullPath: '/dashboard/group-tools'
      preLoaderRoute: typeof DashboardGroupToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardGroupToolsRoute: typeof DashboardGroupToolsRoute
  DashboardPriceListRoute: typeof DashboardPriceListRoute
  DashboardRentalsRoute: typeof DashboardRentalsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStockRoute: typeof DashboardStockRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGroupToolsRoute: DashboardGroupToolsRoute,
  DashboardPriceListRoute: DashboardPriceListRoute,
  DashboardRentalsRoute: DashboardRentalsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStockRoute: DashboardStockRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
